export const lightTheme = {
  colors: {
    white: "#fff",
    black: "#374957",
    main: "#744AD2",
    extraLiteMain: "#E5EEFF",
    accent: "#F3349D",
    extraLiteAccent: "#FFD4E9",
    grey: "#91A6B7",
    mediumGrey: "#B1C1CE",
    liteGrey: "#CFDCE6",
    extraLiteGrey: "#EDF5FD",
    newBg: "#F2FF5C",
    approveBg: "#FBB707",
    printBg: "#FED2FF",
    doneBg: "#CBF45D",
  },
  spacing: {
    xxs: 2,
    xs: 4,
    s: 8,
    m: 12,
    l: 16,
    xl: 20,
    xxl: 24,
  },
  radius: {
    xs: 4,
    s: 6,
    m: 8,
    l: 12,
    xl: 16,
    xxl: 20,
    xxxl: 32,
  },
};
