export const lightTheme = {
  colors: {
    white: "#fff",
    black: "#374957",
    main: "#744AD2",
    extraLiteMain: "#E5EEFF",
    accent: "#F3349D",
    extraLiteAccent: "#FFD4E9",
    grey: "#91A6B7",
    mediumGrey: "#B1C1CE",
    liteGrey: "#CFDCE6",
    extraLiteGrey: "#EDF5FD",
    newBg: "#F2FF5C",
    approveBg: "#FBB707",
    printBg: "#FED2FF",
    doneBg: "#CBF45D",
  },
  spacings: {
    xxs: "2px",
    xs: "4px",
    s: "8px",
    m: "12px",
    l: "16px",
    xl: "20px",
    xxl: "24px",
  },
  radiuses: {
    xs: "4px",
    s: "6px",
    m: "8px",
    l: "12px",
    xl: "16px",
    xxl: "20px",
    xxxl: "32px",
  },
};
